Débora Kocks Nogueira
Stefanie Mayumi
5 CDN - Processamento de Linguagem Natural

- Rodou tudo.
- Perdeu 0.5 ponto na questão 01. Explicação insuficiente. Precisava explicar de onde vem a alta dimensionalidade e relacionar com a existência de muito mais 0s do que 1s etc.
- Perdeu 0.5 na questão 02, 03 e 04. Explicação extremamente concisa, sem exemplos e insuficientes. Conjunto da obra.
- Perdeu 0.5 na questão 05. A principal diferença, entre diversas outras, é não considerar A ordem em que as palavras aparecem. Há outras, mas todas elas advêm do fato de que se trata de representação esparça de primeira geração.
- Perdeu 0.5 na questão 06. Explicação extremamente concisa, sem exemplos e insuficientes. Fala de gravidade mas não explica exatamente como essa revidade é calculada.
- Perdeu 0.5 na questão 09. Precisava explicar que a dimensão vem dos contextos (e não, simplesmente, pelo número de palavras). O contexto são as colunas da matriz. A resposta está incompleta pois assume implicitamente que os contextos são palavras únicas. No entanto, a dimensão do vetor é definida pelo número de contextos possíveis, que depende da modelagem adotada (ex.: unigramas ou n-gramas), não necessariamente sendo igual ao tamanho do vocabulário

# Prática — Teste 01 – Atividade Valendo 40% da Média do Bimestre

## Questão 01 (1.0)
a) Explique o que é uma representação esparsa em PLN e por que a codificação one-hot é considerada esparsa.

b) Na célula abaixo, implemente em Python a codificação one-hot para a lista ["casa", "carro", "filme", "bom", "ruim"] utilizando OneHotEncoder do sklearn e exiba a matriz resultante.

### RESPOSTA

Item (1A)

R. São vetores de alta dimensionalidade. One-hot é considerada esparsa porque quase todas as posições são 0, contendo apena um 1 por token

In [1]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [2]:
# RESPOSTA Item (1B)
# Seu código abaixo:

vocab = ["casa", "carro", "filme", "bom", "ruim"]
index = {w: i for i, w in enumerate(vocab)}

def one_hot(word, vocab_index):
    vec = [0] * len(vocab_index)
    vec[vocab_index[word]] = 1
    return vec

print("Vocabulário:", index)
for w in vocab:
    print(w, "→", one_hot(w, index))

Vocabulário: {'casa': 0, 'carro': 1, 'filme': 2, 'bom': 3, 'ruim': 4}
casa → [1, 0, 0, 0, 0]
carro → [0, 1, 0, 0, 0]
filme → [0, 0, 1, 0, 0]
bom → [0, 0, 0, 1, 0]
ruim → [0, 0, 0, 0, 1]

## Questão 02 (1.0)

a) Explique o que é stemming e qual é seu objetivo no processamento de linguagem natural.

b) Utilizando o NLTK e o RSLPStemmer, aplique stemming ao texto abaixo:
"Os pesquisadores analisavam relatórios e comparavam resultados financeiros."

### RESPOSTA

Item (2A)

R. É uma técnica que reduz palavras à raiz com o objetivo de tratar diferentes formas de uma mesma palavra e facilitar a análise de textos.

In [3]:
# RESPOSTA Item (2B)
# Seu código abaixo:

# Definir o texto base para experimentos iniciais.
texto = "Os pesquisadores analisavam relatórios e comparavam resultados financeiros."
texto

# Tokenizar com NLTK.
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

tokens_nltk = word_tokenize(texto, language='portuguese')
tokens_nltk

# Stemming com RSLPStemmer
nltk.download('rslp')

from nltk.stem import RSLPStemmer

stemmer = RSLPStemmer()
stems = [stemmer.stem(token) for token in tokens_nltk]
list(zip(tokens_nltk, stems))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Unzipping stemmers/rslp.zip.

[('Os', 'os'),
 ('pesquisadores', 'pesquis'),
 ('analisavam', 'analis'),
 ('relatórios', 'relatóri'),
 ('e', 'e'),
 ('comparavam', 'compar'),
 ('resultados', 'result'),
 ('financeiros', 'financ'),
 ('.', '.')]

## Questão 03 (1.0)

a) Explique o que são stopwords em PLN e qual é o objetivo de removê-las durante o processamento de texto.

b) Utilizando o NLTK, realize a remoção de stopwords do texto abaixo e exiba os tokens restantes:
"Os pesquisadores analisavam os dados e comparavam os resultados com os modelos anteriores."

### RESPOSTA

Item (3A)

R. São palavras muito comuns que, em certas tarefas, têm pouca contribuição ao diferenciar documentos. Seu objetivo é diminuir informações desnecessárias e simplificar os dados, mantendo apenas os termos mais relevantes.

In [4]:
# RESPOSTA Item (3B)
# Seu código abaixo:

nltk_dataset = [texto]

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

# Lista de stopwords em português
stop = stopwords.words('portuguese')

for texto in nltk_dataset:
    tokens = word_tokenize(texto, language='portuguese')
    tokens_limpos = []

    for t in tokens:
        if t.lower() not in stop:
            tokens_limpos.append(t)

    print(tokens_limpos)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...

['pesquisadores', 'analisavam', 'relatórios', 'comparavam', 'resultados', 'financeiros', '.']

[nltk_data]   Unzipping corpora/stopwords.zip.

## Questão 04 (1.0)

a) Explique o que é lematização e qual a diferença em relação ao stemming.

b) Utilizando o spaCy, aplique lematização ao texto abaixo e exiba cada token com seu respectivo lema:

### RESPOSTA

Item (4A)

R. Lematização é reduzir palavras à sua forma básica ou dicionário, já o stemming, corta sufixos e pode gerar radicais inválidos.

In [5]:
# RESPOSTA Item (4B)
# Seu código abaixo:

# Instalando o SpaCy
!pip install -U spacy
import spacy

# Baixar modelo em português.
!python -m spacy download pt_core_news_sm

nlp = spacy.load("pt_core_news_sm")

doc = nlp(texto)

lemmas_spacy = [token.lemma_ for token in doc]
list(zip([t.text for t in doc], lemmas_spacy))

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.5.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting pt-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 34.4 MB/s eta 0:00:00
Installing collected packages: pt-core-news-sm
Successfully installed pt-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

[('Os', 'o'),
 ('pesquisadores', 'pesquisador'),
 ('analisavam', 'analisar'),
 ('relatórios', 'relatório'),
 ('e', 'e'),
 ('comparavam', 'comparar'),
 ('resultados', 'resultado'),
 ('financeiros', 'financeiro'),
 ('.', '.')]

## Questão 05 (1.0)

a) Explique o que é o modelo Bag of Words (BoW) e qual sua principal limitação em tarefas de PLN.

b) Utilizando o CountVectorizer do sklearn, aplique BoW ao conjunto de textos abaixo e exiba a matriz resultante e o vocabulário:
textos = [
    "o sistema falhou",
    "o sistema foi atualizado",
    "falha no sistema"
]

### RESPOSTA

Item (5A)

R. O Bag of Words ignora a ordem e a gramática, focando apenas na frequência (contagem) das palavras. Sua principal limitação é a perda do contexto e o significado das frases.

In [6]:
# RESPOSTA Item (5B)
# Seu código abaixo:

from nltk.tokenize import sent_tokenize
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import spacy
import nltk


# Exemplo de parágrafo
textos = """
O sistema falhou.
O sistema foi atualizado.
Falha no sistema.
"""

# Tokenizar em sentenças
sentencas = sent_tokenize(textos, language='portuguese')

# Remover stopwords e lematizar
corpus_sem_stop = []

for texto in sentencas:
    doc = nlp(texto)
    tokens_limpos = [
        token.lemma_
        for token in doc
        if token.is_alpha and not token.is_stop
    ]
    corpus_sem_stop.append(" ".join(tokens_limpos))

print("Corpus processado:", corpus_sem_stop)

# Criar Bag of Words
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus_sem_stop)
feature_names = vectorizer.get_feature_names_out()

# Visualizar a matriz BoW
bow_df = pd.DataFrame(X.toarray(), columns=feature_names)
print("\nVocabulário:", feature_names)
print("\nMatriz BoW:\n", bow_df)

Corpus processado: ['falhar', 'atualizar', 'falha']

Vocabulário: ['atualizar' 'falha' 'falhar']

Matriz BoW:
    atualizar  falha  falhar
0          0      0       1
1          1      0       0
2          0      1       0

## Questão 06 (1.5)

a) Explique o que é TF-IDF e qual é sua principal ideia em relação à importância das palavras em um conjunto de documentos.

b) Compare TF-IDF com Bag of Words (BoW), destacando a principal diferença entre as duas abordagens.

c) Utilizando o TfidfVectorizer do sklearn, aplique TF-IDF ao conjunto de textos abaixo e exiba a matriz resultante e o vocabulário:

textos = [
    "o sistema falhou",
    "o sistema foi atualizado",
    "falha no sistema"
]

### RESPOSTA

Item (6A)

R. O TF-IDF mede a importância de uma palavra em relação ao corpus, aumentando o peso de palavras frequentes no texto e diminuindo o peso de palavras comuns no corpus.

### RESPOSTA

Item (6B)

R. O BoW faz a contagem da frequência das palavras e o TF-IDF a raridade da palavra no corpus

In [7]:
# RESPOSTA Item (6C)
# Seu código abaixo:

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

corpus = [
    "o sistema falhou",
    "o sistema foi atualizado",
    "falha no sistema",
]

corpus

# Visualizar o corpus.
for i, frase in enumerate(corpus, 1):
    print(f"D{i}: {frase}")


# gerar matriz TF-IDF.
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(corpus)

tfidf = pd.DataFrame(
    X_tfidf.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=[f"D{i+1}" for i in range(len(corpus))]
)

tfidf

D1: o sistema falhou
D2: o sistema foi atualizado
D3: falha no sistema

    atualizado     falha    falhou       foi        no   sistema
D1    0.000000  0.000000  0.861037  0.000000  0.000000  0.508542
D2    0.652491  0.000000  0.000000  0.652491  0.000000  0.385372
D3    0.000000  0.652491  0.000000  0.000000  0.652491  0.385372

## Questão 07 (1.5)

a) Explique o que é PMI (Pointwise Mutual Information) e qual é sua finalidade no processamento de linguagem natural.

b) Considerando as probabilidades abaixo, determine se “gato” e “leite” são independentes ou dependentes. Justifique sua resposta com base no conceito de independência de probabilidades:
P(gato) = 0,2
P(leite) = 0,5
P(gato, leite) = 0,1

c) Implemente em Python uma função que receba P(w, c), P(w) e P(c) e retorne o PMI correspondente.

### RESPOSTA

Item (7A)

R. Representa quantas vezes palavras aparecem próximas umas das outras no corpus, utilizando uma janela de contexto. Seu objetivo é identificar palavras que coocorrem significativamente, ajudando a capturar relações semânticas entre termos.

### RESPOSTA

Item (7B)

R. Gato e leite são independentes. A probabilidade de ocorrer “gato” e “leite” juntos é exatamente igual ao produto das probabilidades individuais.

In [8]:
# RESPOSTA  Item (7C)
# Seu código abaixo:

# Corpus
corpus = [
    "gato bebe agua",
    "cachorro bebe agua",
    "gato bebe leite",
    "cachorro bebe leite",
    "gato come peixe",
    "cachorro come peixe",
    "gato come carne",
    "cachorro come carne",
    "homem bebe agua",
    "homem come carne",
]

# Visualizar o corpus.
for i, frase in enumerate(corpus, 1):
    print(f"D{i}: {frase}")

import numpy as np
import pandas as pd

# Gerar bigramas sequenciais (janela de contexto = "1 à direita").
from nltk.util import bigrams

bigrams_list = []
for sent in corpus:
    tokens = sent.split()
    bigrams_list.extend(list(bigrams(tokens)))

bigrams_list

# Contar frequência dos bigramas.
from collections import Counter

bigram_freq = Counter(bigrams_list)
bigram_freq

# Criar matriz de coocorrência a partir dos bigramas.
words = sorted(set([w for bg in bigram_freq for w in bg]))
matrix = pd.DataFrame(0, index=words, columns=words)

for (w,c), freq in bigram_freq.items():
    matrix.loc[w,c] = freq

matrix

# Gerar matriz de probabilidade conjunta.
N = matrix.values.sum()
p_wc = matrix / N
p_wc

# Calcular frequência marginal das palavras.
p_w = matrix.sum(axis=1) / N
p_w

# Calcular frequência marginal dos contextos.
p_c = matrix.sum(axis=0) / N
p_c

# Calcular PMI (Pointwise Mutual Information).
pmi = np.log(p_wc / (p_w.values[:, None] * p_c.values[None, :]))
pmi = pmi.replace([np.inf, -np.inf], 0)
pmi

D1: gato bebe agua
D2: cachorro bebe agua
D3: gato bebe leite
D4: cachorro bebe leite
D5: gato come peixe
D6: cachorro come peixe
D7: gato come carne
D8: cachorro come carne
D9: homem bebe agua
D10: homem come carne

/usr/local/lib/python3.12/dist-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)

,agua,bebe,cachorro,carne,come,gato,homem,leite,peixe
agua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bebe,1.386294,0.000000,NaN,0.000000,0.000000,NaN,NaN,1.386294,0.000000
cachorro,0.000000,0.693147,NaN,0.000000,0.693147,NaN,NaN,0.000000,0.000000
carne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
come,0.000000,0.000000,NaN,1.386294,0.000000,NaN,NaN,0.000000,1.386294
gato,0.000000,0.693147,NaN,0.000000,0.693147,NaN,NaN,0.000000,0.000000
homem,0.000000,0.693147,NaN,0.000000,0.693147,NaN,NaN,0.000000,0.000000
leite,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
peixe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Questão 08 (1.0)

a) Explique o que representa uma matriz palavra-contexto baseada em PMI e qual seu objetivo em PLN.

b) Utilizando Python, construa uma matriz palavra-contexto com PMI para o conjunto de textos abaixo. Considere como contexto as palavras que aparecem no mesmo documento.

textos = [
    "gato bebe leite",
    "cachorro bebe água",
    "gato come peixe"
]

### RESPOSTA

Item (8A)

R. A matriz palavra-contexto registra quantas vezes uma palavra
aparece próxima de outra dentro de um corpus. Seu objetivo é capturar o significado das palavras analisando com quais outras palavras elas aparecem próximas em um corpus.

In [9]:
# RESPOSTA Item (8B)
# Seu código abaixo:

# Corpus
corpus = [
    "gato bebe leite",
    "cachorro bebe agua",
    "gato come peixe",
]

# Visualizar o corpus.
for i, frase in enumerate(corpus, 1):
    print(f"D{i}: {frase}")

import numpy as np
import pandas as pd

# Gerar bigramas sequenciais (janela de contexto = "1 à direita").
from nltk.util import bigrams

bigrams_list = []
for sent in corpus:
    tokens = sent.split()
    bigrams_list.extend(list(bigrams(tokens)))

bigrams_list

# Contar frequência dos bigramas.
from collections import Counter

bigram_freq = Counter(bigrams_list)
bigram_freq

# Criar matriz de coocorrência a partir dos bigramas.
words = sorted(set([w for bg in bigram_freq for w in bg]))
matrix = pd.DataFrame(0, index=words, columns=words)

for (w,c), freq in bigram_freq.items():
    matrix.loc[w,c] = freq

matrix

# Gerar matriz de probabilidade conjunta.
N = matrix.values.sum()
p_wc = matrix / N
p_wc

# Calcular frequência marginal das palavras.
p_w = matrix.sum(axis=1) / N
p_w

# Calcular frequência marginal dos contextos.
p_c = matrix.sum(axis=0) / N
p_c

# Calcular PMI (Pointwise Mutual Information).
pmi = np.log(p_wc / (p_w.values[:, None] * p_c.values[None, :]))
pmi = pmi.replace([np.inf, -np.inf], 0)
pmi

D1: gato bebe leite
D2: cachorro bebe agua
D3: gato come peixe

/usr/local/lib/python3.12/dist-packages/pandas/core/internals/blocks.py:393: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)

              agua      bebe  cachorro      come  gato     leite     peixe
agua           NaN       NaN       NaN       NaN   NaN       NaN       NaN
bebe      1.098612  0.000000       NaN  0.000000   NaN  1.098612  0.000000
cachorro  0.000000  1.098612       NaN  0.000000   NaN  0.000000  0.000000
come      0.000000  0.000000       NaN  0.000000   NaN  0.000000  1.791759
gato      0.000000  0.405465       NaN  1.098612   NaN  0.000000  0.000000
leite          NaN       NaN       NaN       NaN   NaN       NaN       NaN
peixe          NaN       NaN       NaN       NaN   NaN       NaN       NaN

## Questão 09 (1.0)
NÃO HÁ IMPLEMENTAÇÃO NESTA QUESTÃO.

a) Em uma matriz palavra-contexto baseada em PMI, explique o que representa os vetores das palavras (as linhas ou as colunas).

b) Considerando essa matriz, o que define a dimensão de cada vetor?

### RESPOSTA

Item (9A)

R. Os vetores das palavras são representados pelas linhas da matriz.

### RESPOSTA

Item (9B)

R. A dimensão de cada vetor é definida pelo tamanho do vocabulário (o número de palavras únicas usadas como contexto).